FROM continuumio/miniconda3:4.1.11
MAINTAINER Robert Cohn <Robert.S.Cohn@intel.com>

# This file is automatically generated from tpl.Dockerfile

ENV ACCEPT_INTEL_PYTHON_EULA=yes

RUN conda config --add channels intel \
    && conda install -y -q intelpython{{pyver}}_{{package}}={{release}} python={{pyver}}

